version: '3.7'

name: 'balance'

services:
  db:
    container_name: db_balance
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      -  postgres_data:/var/lib/postgresql/data
    networks:
      - backend 

volumes:
  postgres_data:

networks:
  backend: